set(SDL3_DIR "${ENGINE_ROOT}/libraries/SDL/install/lib/cmake/SDL3")
set(SDL3_LIB "${ENGINE_ROOT}/libraries/SDL/install/lib/libSDL3.so")
set(SDL3_INCLUDE_DIRS "${ENGINE_ROOT}/libraries/SDL/install/include")
set(box2d_DIR "${ENGINE_ROOT}/libraries/box2d/install/lib/cmake/box2d")
set(box2d_LIB "${ENGINE_ROOT}/libraries/box2d/install/lib/libbox2d.a")
set(box2d_INCLUDE_DIRS "${ENGINE_ROOT}/libraries/box2d/install/include")