set(SDL3_DIR "${ENGINE_ROOT}/libraries/SDL/install/cmake")
set(SDL3_INCLUDE_DIRS "${ENGINE_ROOT}/libraries/SDL/install/include")
set(SDL3_BIN "${ENGINE_ROOT}/libraries/SDL/install/bin")
set(SDL3_image_DIR "${ENGINE_ROOT}/libraries/SDL_Image/install/cmake")
set(SDLIMAGE_INCLUDE_DIR "${ENGINE_ROOT}/libraries/SDL_Image/install/include")
set(SDL3_image_BIN "${ENGINE_ROOT}/libraries/SDL_Image/install/bin")
set(box2d_DIR "${ENGINE_ROOT}/libraries/box2d/install/lib/cmake/box2d")
set(box2d_INCLUDE_DIRS "${ENGINE_ROOT}/libraries/box2d/install/include")    